In [2]:
import pandas as pd
df=pd.read_csv('cleaned_data.csv')

print(df.isnull().sum())
print(df.duplicated().sum())
df.sample(10)

answers    0
label      0
dtype: int64
0

                                                 answers  label
43865  ['Yes, making extra mortgage payments can lowe...      1
45092  ["I'm sorry to hear about your arm and wrist p...      1
1940   ['A bit is an on / off switch , zero or 1 . A ...      0
37936  ["Sleeping with a hand under your head is a ha...      1
6448   ['because there are business owners and stockh...      0
13426  ["Over the last couple of centuries , we ( peo...      0
35728  ['LED light bulbs are more expensive than LED ...      1
4149   ['Until a better answer comes , the usual pers...      0
6966   ["Liking anime largely is n't . Obsessing over...      0
41996  ['As an F1 student on Optional Practical Train...      1

In [3]:
import ast

def clean_text(x):
    if isinstance(x, list):
        return " ".join(map(str, x))

    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)

            if isinstance(parsed, list):
                return " ".join(map(str, parsed))
            else:
                return str(parsed)

        except:
            return x   # IMPORTANT: fallback safe

    return str(x)

In [4]:
df['answers'] = df['answers'].str.lower()
df['answers']=df['answers'].apply(clean_text)

df.head()

                                             answers  label
0  basically there are many categories of " best ...      0
1  salt is good for not dying in car crashes and ...      0
2  the way it works is that old tv stations got a...      0
3  you ca n't just go around assassinating the le...      0
4  wanting to kill the shit out of germans drives...      0

In [5]:
df_feat = df.copy()
df_feat.sample(5)

                                                 answers  label
21528  hi... it will definitely stop.i do not think y...      0
1645   * * like . you . are . five . * * there are lo...      0
19337  this site should help you to accomplish what y...      0
11442  " the first thing you need to know about the i...      0
19136  if you do not need it for a day or a week or s...      0

In [6]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [9]:
def load_word_list(path):
    with open(path, "r", encoding="utf-8") as f:
        return set(line.strip().lower() for line in f if line.strip())

chat_words = load_word_list("chat_words.txt")
function_words = load_word_list("function_words.txt")
discourse_markers = load_word_list("discourse_markers.txt")