In [23]:
import pandas as pd
df=pd.read_csv('/hc3_all.csv')
df.head()

,id,question,human_answers,chatgpt_answers,source,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,0,"Why is every book I hear about a "" NY Times # ...","['Basically there are many categories of "" Bes...",['There are many different best seller lists t...,reddit_eli5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"If salt is so bad for cars , why do we use it ...",['salt is good for not dying in car crashes an...,"[""Salt is used on roads to help melt ice and s...",reddit_eli5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Why do we still have SD TV channels when HD lo...,"[""The way it works is that old TV stations got...","[""There are a few reasons why we still have SD...",reddit_eli5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Why has nobody assassinated Kim Jong - un He i...,"[""You ca n't just go around assassinating the ...",['It is generally not acceptable or ethical to...,reddit_eli5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,How was airplane technology able to advance so...,['Wanting to kill the shit out of Germans driv...,['After the Wright Brothers made the first pow...,reddit_eli5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.drop(columns=[col for col in df.columns if "Unnamed" in col or col in ["id", "source"]], inplace=True)
df.head()
print(df.shape)
df.to_csv("cleaned_data.csv",index=False)

(24325, 3)

In [25]:
df.isnull().sum()

df.dropna()

,question,human_answers,chatgpt_answers
0,"Why is every book I hear about a "" NY Times # ...","['Basically there are many categories of "" Bes...",['There are many different best seller lists t...
1,"If salt is so bad for cars , why do we use it ...",['salt is good for not dying in car crashes an...,"[""Salt is used on roads to help melt ice and s..."
2,Why do we still have SD TV channels when HD lo...,"[""The way it works is that old TV stations got...","[""There are a few reasons why we still have SD..."
3,Why has nobody assassinated Kim Jong - un He i...,"[""You ca n't just go around assassinating the ...",['It is generally not acceptable or ethical to...
4,How was airplane technology able to advance so...,['Wanting to kill the shit out of Germans driv...,['After the Wright Brothers made the first pow...
...,...,...,...
24320,Is rise in pressure from 116/66 to 140/80 norm...,['Hello!Welcome and thank you for asking on HC...,"[""It's not uncommon for blood pressure to fluc..."
24321,What could cause a painless lump in the right ...,"['Hi, * As per my surgical experience, the iss...",['There are several possible causes of a painl...
24322,Can Acutret be given to a child for treatment ...,['Although it is difficult to comment whether ...,"[""It is not appropriate for me to recommend a ..."
24323,Are BP of 119/65 and pulse of 35 causes for co...,['Welcome and thank you for asking on HCM! I h...,['It is not uncommon for people with rheumatoi...
24324,Suggest treatment for back pain after walking ...,"['Hi,Having this type of back pain at this age...","['It is not uncommon to experience back pain, ..."