In [9]:
import pandas as pd
df=pd.read_csv('hc3_all.csv')
df.head()

,id,question,human_answers,chatgpt_answers,source
0,0,"Why is every book I hear about a "" NY Times # ...","['Basically there are many categories of "" Bes...",['There are many different best seller lists t...,reddit_eli5
1,1,"If salt is so bad for cars , why do we use it ...",['salt is good for not dying in car crashes an...,"[""Salt is used on roads to help melt ice and s...",reddit_eli5
2,2,Why do we still have SD TV channels when HD lo...,"[""The way it works is that old TV stations got...","[""There are a few reasons why we still have SD...",reddit_eli5
3,3,Why has nobody assassinated Kim Jong - un He i...,"[""You ca n't just go around assassinating the ...",['It is generally not acceptable or ethical to...,reddit_eli5
4,4,How was airplane technology able to advance so...,['Wanting to kill the shit out of Germans driv...,['After the Wright Brothers made the first pow...,reddit_eli5

In [10]:

df.drop(columns=[col for col in df.columns if "Unnamed" in col or col in ["id", "source","question"]], inplace=True)

print(df.shape)
df.to_csv("cleaned_data.csv",index=False)
df.head()

(24322, 2)

,human_answers,chatgpt_answers
0,"['Basically there are many categories of "" Bes...",['There are many different best seller lists t...
1,['salt is good for not dying in car crashes an...,"[""Salt is used on roads to help melt ice and s..."
2,"[""The way it works is that old TV stations got...","[""There are a few reasons why we still have SD..."
3,"[""You ca n't just go around assassinating the ...",['It is generally not acceptable or ethical to...
4,['Wanting to kill the shit out of Germans driv...,['After the Wright Brothers made the first pow...

In [11]:
human_df = df[['human_answers']].copy()
human_df.rename(columns={'human_answers': 'answers'}, inplace=True)
human_df['label'] = 0
ai_df = df[['chatgpt_answers']].copy()
ai_df.rename(columns={'chatgpt_answers': 'answers'}, inplace=True)
ai_df['label'] = 1
df_final = pd.concat([human_df, ai_df], ignore_index=True)

df_final.to_csv("cleaned_data.csv",index=False)
df_final.head()

                                             answers  label
0  ['Basically there are many categories of " Bes...      0
1  ['salt is good for not dying in car crashes an...      0
2  ["The way it works is that old TV stations got...      0
3  ["You ca n't just go around assassinating the ...      0
4  ['Wanting to kill the shit out of Germans driv...      0

In [12]:
df=df_final
df.head()

                                             answers  label
0  ['Basically there are many categories of " Bes...      0
1  ['salt is good for not dying in car crashes an...      0
2  ["The way it works is that old TV stations got...      0
3  ["You ca n't just go around assassinating the ...      0
4  ['Wanting to kill the shit out of Germans driv...      0

In [16]:
df.isnull().values.any()
df.duplicated().any()
df.duplicated().sum()

np.int64(2894)

In [ ]:
df[df.duplicated(keep=False)]

                                                 answers  label
3106   ['Ok so you \'ve got your red wines and your w...      0
3107   ['The 9/10 is actually part of the dollar amou...      0
3108   ["Because we do n't use weight to lift . We us...      0
3109   ['It takes anywhere from 2 to 10 years to make...      0
3110   ['There are 3 big Operating systems(Think of a...      0
...                                                  ...    ...
47440  ['!\nToo many requests in 1 hour. Try again la...      1
47826  ['!\nOnly one message at a time. Please allow ...      1
48154                                               ['']      1
48320  ['!\nnetwork error\n\n\n\nThere was an error g...      1
48342                                               ['']      1

[5274 rows x 2 columns]