In [1]:
import pandas as pd
df=pd.read_csv('cleaned_data.csv')

print(df.isnull().sum())
print(df.duplicated().sum())
df.sample(10)

answers    0
label      0
dtype: int64
0

                                                 answers  label
36676  ['Car sickness, also known as motion sickness,...      1
32108  ["In the United States, the two major politica...      1
6227   ['Eating sub optimally does not mean a swift c...      0
35885  ['A randomize function is a function in progra...      1
16566  ['The sample complexity of a machine learning ...      0
10667  ['The makers of adblocking software often grac...      0
27190  ["Osmosis is a natural process that occurs whe...      1
26554  ["If the Earth stopped spinning, a lot of thin...      1
40184  ['A software agent is a program that performs ...      1
28494  ['Feeling good is a sensation that is usually ...      1

In [2]:
import ast

def clean_text(x):
    if isinstance(x, list):
        return " ".join(map(str, x))

    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)

            if isinstance(parsed, list):
                return " ".join(map(str, parsed))
            else:
                return str(parsed)

        except:
            return x   # IMPORTANT: fallback safe

    return str(x)

In [3]:
df['answers'] = df['answers'].str.lower()
df['answers']=df['answers'].apply(clean_text)

df.head()

                                             answers  label
0  basically there are many categories of " best ...      0
1  salt is good for not dying in car crashes and ...      0
2  the way it works is that old tv stations got a...      0
3  you ca n't just go around assassinating the le...      0
4  wanting to kill the shit out of germans drives...      0

In [4]:
df_feat = df.copy()
df_feat.sample(5)

                                                 answers  label
7537   [ google maps calculates distance based on an ...      0
14652  a nation is a group of people with several fac...      0
25446  free web browsers like opera generate income t...      1
25116  encryption is a way of hiding information so t...      1
43965  to remove the effect of the overall stock mark...      1

In [6]:
import spacy
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])
nlp.add_pipe("sentencizer")

In [8]:
def load_word_list(path):
    with open(path, "r", encoding="utf-8") as f:
        return set(line.strip().lower() for line in f if line.strip())

chat_words = load_word_list("chat_words.txt")
function_words = load_word_list("function_words.txt")
discourse_markers = load_word_list("discourse_markers.txt")

In [9]:
def split_sentences(text):
    doc = nlp(text)
    return [sent.text.strip() for sent in doc.sents if sent.text.strip()]