In [2]:
import pandas as pd
df=pd.read_csv('cleaned_data.csv')

print(df.isnull().sum())
print(df.duplicated().sum())
df.sample(10)

answers    0
label      0
dtype: int64
0

                                                 answers  label
14236  ["Hypnotism is your capacity to accept suggest...      0
1483   ['Well , this is kind of an interesting topic ...      0
29984  ['When a can of compressed gas is used, the ga...      1
21157  ['If the investments are in a non-retirement, ...      0
31979  ['Trolls are a part of Norwegian folklore and ...      1
32852  ['Autism is a condition that affects how a per...      1
38401  ['When you feel nervous or anxious, your body ...      1
25018  ['Sure! Reddit is a website where people can s...      1
22402  ['hello thanks for the consult at hcm..plz don...      0
41494  ['Yes, there are several debit cards that offe...      1

In [ ]:
import ast

def clean_text(x):
    if isinstance(x, list):
        return " ".join(map(str, x))

    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)

            if isinstance(parsed, list):
                return " ".join(map(str, parsed))
            else:
                return str(parsed)

        except:
            return x   # IMPORTANT: fallback safe

    return str(x)

In [22]:
df['answers'] = df['answers'].str.lower()
df['answers']=df['answers'].apply(clean_text)

df.head()

                                             answers  label
0  basically there are many categories of " best ...      0
1  salt is good for not dying in car crashes and ...      0
2  the way it works is that old tv stations got a...      0
3  you ca n't just go around assassinating the le...      0
4  wanting to kill the shit out of germans drives...      0

In [23]:
df_feat = df.copy()
df_feat.sample(5)

                                                 answers  label
21896  hi...by what you quote it seems like an insect...      0
25234  chinese buffets often offer a large selection ...      1
11417  when the anti - virus software is running , it...      0
29226  when a large ship is completed, it is usually ...      1
32408  it's possible that your cat is showing affecti...      1